version: "3.8"

services:
  logto:
    restart: always
    image: svhd/logto:1.18.0
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3010:3010
      - 3011:3011
    volumes:
      - "./.volumes/logto_db:/var/lib/logto"
    environment:
      - TRUST_PROXY_HEADER=1
      # Logto supports SQLite natively via sqlite:// URL scheme or implicitly by omitting DB_URL for a local sqlite
      - DB_URL=sqlite:////var/lib/logto/logto.db
      - PORT=3010
      - ADMIN_PORT=3011
      - ENDPOINT
      - ADMIN_ENDPOINT
